name: resty

on: push

jobs:
  build-test-deploy:
  steps: 
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set-up Node
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"
    - run: npm install
    - run: npm run build
    - run: npm test
    - name: Deploy
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: public
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

